#PT-BR | Você só pode editar o que está dentro das aspas!
#Placeholders: {player} = executador do comando
#Warn
w-uso: "§cUso /warn, /aviso ou /av <mensagem>"
w-warn: "§8[§c§lAVISO§8] §l•§r§l "
w-ms: "§c§lEnviou um aviso no chat!"
#Alert
a-uso: "§cUso /alert, /alerta ou /al <mensagem>"
a-alert: "§8[§c§lALERTA§8] §l•§r§l " 
a-ms: "§c§lEnviou um alerta no chat!"
#Reload
reload: "§a{player} §cConfig.yml foi recarregado com sucesso!"
##Warn, Alert e Reload
erro2: "§cVocê não possui permissão para executar esse Comando!"
erro1: "§cEsse comando so pode ser executado por Jogadores!"
#Warn and Alert cor do nome do jogador
color: "§4§l"
