#EN | You can only edit what's inside the quotes!
#Placeholders: {player} = command executor
#Warn
w-uso: "§cUsage /warn or /w <message>"
w-warn: "§8[§c§lWARNING§8] §l•§r§l "
w-ms: "§c§lSent a warning in the chat!"
#Alert
a-uso: "§cUsage /alert or /al <message>"
a-alert: "§8[§c§lALERT§8] §l•§r§l " 
a-ms: "§c§lSent an alert in the chat!"
#Reload
reload: "§a{player} §cConfig.yml was successfully reloaded!"
#Warn, Alert and Reload
erro2: "§cYou do not have permission to execute this command!"
erro1: "§cThis command can only be run by the players!"
#Warn and Alert player name color
color: "§4§l"
