main: net.sad_software.alert.Alert
name: S-Alert
version: 1.5
depend: [TitleAPI]
author: LostConnection
website: https://github.com/NioiOtaku/S-Alert/
commands:
   warn:
      aliases: [aviso, av, w]
   alert:
      aliases: [alerta, al]
   s-reload:
      aliases: [sr]